# Generated by Django 4.1.4 on 2022-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='content',
            field=models.CharField(default='programming', max_length=100),
            preserve_default=False,
        ),
    ]
